### PR TITLE
608 duplicate key stuff from django connectwise to django autotask

### PR DESCRIPTION
**Pull request by camsweeney**
Started integrating files for django-autotask, replacing django-connectwise with django-autotask.

### CODE REVIEW

**Comment by samj-w** [comment]
Small things first:
* In `.coveragerc` build is not indented
* In `README.md` the copyright says 2017, but maybe should be 2018? This question is more for @kti-matt

Only big thing that stuck out was in `runtests.py`, 
 `AUTOTASK_CREDENTIALS={
          'company_id': 'training',
          'integrator_login_id': '',
          'integrator_password': '',
          'api_public_key': '',
          'api_private_key': '',
          'api_codebase': 'v4_6_release',
      }`

This appears to be connectwise specific, or at least some of it is connectwise specific. I don't know the autotaskAPI, but I'm pretty it wouldn't use these and I know it wont use `v4_6_release`. It should probably be removed/made blank just to avoid confusion in the future. There might be more, but I couldn't find any right now.

**Comment by kti-matt** [comment]
Yeah, year should be updated. For stuff in runtests.py, either remove them completely (they would be added back in some later change) or put in placeholders for the actual AT creds. I think it's just username and password?

**Comment by camsweeney** [comment]
I fixed what you mentioned and removed some more stuff from runtests.py. Not sure if there's more to get rid of

**Comment by samj-w** [comment]
Oh sorry, forgot to say earlier. Reviewed again and it looks good to me. I don't have the ability to merge though, but you are clear to merge whenever @kti-matt

**Pull request merged**
